const players = [
  {
    name: "Kevin De Bruyne",
    position: "M/AM RLC",
    age: 31,
    ca: 189,
    pa: 189,
    nationality: "Belgium",
    club: "Manchester City",
    corners: 14,
    crossing: 19,
    dribbling: 15,
    finishing: 16,
    firstTouch: 16,
    freeKickTaking: 17,
    heading: 6,
    longShots: 17,
    longThrows: 7,
    marking: 9,
    passing: 18,
    penaltyTaking: 16,
    tackling: 9,
    technique: 18,
    aggression: 12,
    anticipation: 14,
    bravery: 13,
    composure: 15,
    concentration: 15,
    vision: 20,
    decision: 18,
    determination: 17,
    flair: 16,
    leadership: 9,
    offTheBall: 18,
    positioning: 12,
    teamwork: 14,
    workRate: 13,
    acceleration: 14,
    agility: 11,
    balance: 14,
    jumpingReach: 15,
    naturalFitness: 15,
    pace: 13,
    stamina: 14,
    strength: 10,
    stability: 16,
    foul: 14,
    contestPerformance: 11,
    injury: 14,
    diversity: 10,
    aerialReach: 13,
    commandOfArea: 17,
    communication: 13,
    eccentricity: 12,
    handling: 15,
    kicking: 7,
    oneOnOnes: 14,
    reflexes: 15,
    rushingOut: 15,
    punching: 7,
    throwing: 14,
    adaptation: 11,
    ambition: 14,
    argue: 12,
    loyal: 15,
    resistantToStress: 13,
    professionalism: 15,
    sportsmanship: 15,
    emotionalControl: 20,
    gk: 14,
    dl: 12,
    dc: 10,
    dr: 16,
    wbl: 14,
    wbr: 16,
    dm: 13,
    ml: 12,
    mc: 15,
    mr: 18,
    aml: 16,
    amc: 13,
    amr: 14,
    st: 11,
    height: 14,
    weight: 10,
    leftFoot: 16,
    rightFoot: 14,
    values: 12,
    currentReputation: 15,
    domesticReputation: 15,
    worldReputation: 20,
    race: "Northern European",
    rca: 4,
    colourOfSkin: 1991 / 6 / 28,
    dateOfBirth: 91,
    numberOfNationalTeamAppearances: 24,
    goalsScoredForTheNationalTeam: 394372,
    salary: 18004457,
    rentalClub: null,
    uid: 18004457,
  },
  {
    name: "Kylian Mbappé",
    position: "AM/S RL",
    age: 23,
    ca: 188,
    pa: 197,
    nationality: "France",
    club: "Paris Saint-Germain",
    corners: 13,
    crossing: 13,
    dribbling: 18,
    finishing: 17,
    firstTouch: 18,
    freeKickTaking: 12,
    heading: 7,
    longShots: 13,
    longThrows: 4,
    marking: 4,
    passing: 15,
    penaltyTaking: 18,
    tackling: 4,
    technique: 15,
    aggression: 18,
    anticipation: 14,
    bravery: 15,
    composure: 18,
    concentration: 15,
    vision: 15,
    decision: 18,
    determination: 13,
    flair: 18,
    leadership: 4,
    offTheBall: 17,
    positioning: 6,
    teamwork: 17,
    workRate: 12,
    acceleration: 10,
    agility: 15,
    balance: 15,
    jumpingReach: 15,
    naturalFitness: 18,
    pace: 18,
    stamina: 15,
    strength: 18,
    stability: 15,
    foul: 18,
    contestPerformance: 4,
    injury: 17,
    diversity: 6,
    aerialReach: 16,
    commandOfArea: 16,
    communication: 18,
    eccentricity: 13,
    handling: 18,
    kicking: 8,
    oneOnOnes: 15,
    reflexes: 17,
    rushingOut: 6,
    punching: 16,
    throwing: 7,
    adaptation: 3,
    ambition: 2,
    argue: 2,
    loyal: 3,
    resistantToStress: 3,
    professionalism: 2,
    sportsmanship: 1,
    emotionalControl: 1,
    gk: 2,
    dl: 1,
    dc: 1,
    dr: 2,
    wbl: 3,
    wbr: 2,
    dm: 1,
    ml: 2,
    mc: 2,
    mr: 3,
    aml: 2,
    amc: 1,
    amr: 1,
    st: 2,
    height: 1,
    weight: 10,
    leftFoot: 18,
    rightFoot: 12,
    values: 15,
    currentReputation: 20,
    domesticReputation: 8,
    worldReputation: 14,
    race: "African Caribbean",
    rca: 13,
    colourOfSkin: "1998/12/20",
    dateOfBirth: 57,
    numberOfNationalTeamAppearances: 27,
    goalsScoredForTheNationalTeam: 1035616,
    salary: null,
    rentalClub: null,
    uid: 85139014,
  },
];

function getPlayer(id) {
  // Find a player with the specified ID or return null if not found
  return players.find((player) => player.uid == id) || null;
}

export { getPlayer };
