import { NextPage } from "next";
import Head from "next/head";
const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>my-app</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <section className="header relative pt-16 items-center flex h-screen max-h-860-px"></section>
    </>
  );
};

export default Index;
